
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: messaging_app_development
  username: postgres
  password: Abby2020#

test:
  <<: *default
  database: messaging_app_test
  username: postgres
  password: Abby2020#

production:
  <<: *default
  database: messaging_app_production
  username: messaging_app
  password: <%= ENV["MESSAGING_APP_DATABASE_PASSWORD"] %>
